### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by aj-ptw** [maxsivkov/node-edflib#1]
I tried to run an `npm install` does not work, nan-check throws too many errors.

Is there any chance @maxsivkov could take a look?

Thanks!

**Comment by maxsivkov** [comment]
Hello, please wait couple of hours. I'll take a look

**Comment by maxsivkov** [comment]
It should work now
I tested it under v4.2.6 and v8.10.0
Please confirm.

**Comment by aj-ptw** [comment]
Still does not work on `9.5.0`

here is the error message:

```
$ npm install

> node-edflib@1.0.0 install /Users/andrewkeller/dev/node-edflib
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/edflib/src/edflib_wrapper.o
In file included from ../src/edflib_wrapper.cc:4:
In file included from ../src/edf_wrapper.h:8:
In file included from ../node_modules/nan-check/nan-check.h:17:
../node_modules/nan-marshal/nan-marshal.h:506:21: error: cannot use 'throw' with
      exceptions disabled
                    throw MarshalException("Underlying instance is not a...
                    ^
../node_modules/nan-marshal/nan-marshal.h:512:21: error: cannot use 'throw' with
      exceptions disabled
                    throw MarshalException("Object does not contains property");
                    ^
../node_modules/nan-marshal/nan-marshal.h:537:17: error: cannot use 'throw' with
      exceptions disabled
                throw MarshalException("Argument is not a boolean");
                ^
../node_modules/nan-marshal/nan-marshal.h:546:17: error: cannot use 'throw' with
      exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
../node_modules/nan-marshal/nan-marshal.h:555:17: error: cannot use 'throw' with
      exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
../node_modules/nan-marshal/nan-marshal.h:564:17: error: cannot use 'throw' with
      exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
In file included from ../src/edflib_wrapper.cc:4:
In file included from ../src/edf_wrapper.h:8:
../node_modules/nan-check/nan-check.h:164:13: error: cannot use 'try' with
      exceptions disabled
            try
            ^
../node_modules/nan-check/nan-check.h:267:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:282:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:296:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:310:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:325:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:339:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_...
                ^
../node_modules/nan-check/nan-check.h:360:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(args.Length(), count);
                ^
../node_modules/nan-check/nan-check.h:371:17: error: cannot use 'throw' with
      exceptions disabled
                throw CheckException(args.Length(), { argsCount1, argsCount2 });
                ^
../node_modules/nan-check/nan-check.h:393:9: error: cannot use 'try' with
      exceptions disabled
        try
        ^
../node_modules/nan-check/nan-check.h:427:16: warning: moving a temporary object
      prevents copy elision [-Wpessimizing-move]
        return std::move(CheckArguments(args));
               ^
../node_modules/nan-check/nan-check.h:427:16: note: remove std::move call here
        return std::move(CheckArguments(args));
               ^~~~~~~~~~                    ~
In file included from ../src/edflib_wrapper.cc:4:
../src/edf_wrapper.h:361:7: error: cannot use 'throw' with exceptions disabled
                                                throw std::logic_error(E...
                                                ^
../src/edf_wrapper.h:364:10: error: cannot use 'throw' with exceptions disabled
                                else throw std::logic_error(ERR_NOT_ARRAY);
                                     ^
../src/edf_wrapper.h:369:5: error: cannot use 'throw' with exceptions disabled
                                throw std::logic_error(ERR_WRONG_SIGNAL_LENGTH);
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/edflib/src/edflib_wrapper.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/andrewkeller/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewkeller/dev/node-edflib
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/bin/npm" "install"
npm ERR! node v9.5.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-edflib@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-edflib@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-edflib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-edflib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-edflib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewkeller/dev/node-edflib/npm-debug.log
```

**Comment by aj-ptw** [comment]
I tried with `8.1.2` as well, are you using windows? I'm on a mac

**Comment by aj-ptw** [comment]
here is with `8.10.0`

```bash
$ npm install

> node-edflib@1.0.0 install /Users/andrewkeller/dev/node-edflib
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/edflib/src/edflib_wrapper.o
In file included from ../src/edflib_wrapper.cc:4:
In file included from ../src/edf_wrapper.h:8:
In file included from ../node_modules/nan-check/nan-check.h:17:
../node_modules/nan-marshal/nan-marshal.h:506:21: error: cannot use 'throw' with exceptions disabled
                    throw MarshalException("Underlying instance is not an object");
                    ^
../node_modules/nan-marshal/nan-marshal.h:512:21: error: cannot use 'throw' with exceptions disabled
                    throw MarshalException("Object does not contains property");
                    ^
../node_modules/nan-marshal/nan-marshal.h:537:17: error: cannot use 'throw' with exceptions disabled
                throw MarshalException("Argument is not a boolean");
                ^
../node_modules/nan-marshal/nan-marshal.h:546:17: error: cannot use 'throw' with exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
../node_modules/nan-marshal/nan-marshal.h:555:17: error: cannot use 'throw' with exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
../node_modules/nan-marshal/nan-marshal.h:564:17: error: cannot use 'throw' with exceptions disabled
                throw MarshalException("Argument is not a number");
                ^
In file included from ../src/edflib_wrapper.cc:4:
In file included from ../src/edf_wrapper.h:8:
../node_modules/nan-check/nan-check.h:164:13: error: cannot use 'try' with exceptions disabled
            try
            ^
../node_modules/nan-check/nan-check.h:267:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates IsBuffer check");
                ^
../node_modules/nan-check/nan-check.h:282:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates IsFunction check");
                ^
../node_modules/nan-check/nan-check.h:296:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates IsArray check");
                ^
../node_modules/nan-check/nan-check.h:310:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates IsObject check");
                ^
../node_modules/nan-check/nan-check.h:325:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates IsString check");
                ^
../node_modules/nan-check/nan-check.h:339:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(std::string("Argument ") + std::to_string(mArgIndex) + " violates NotNull check");
                ^
../node_modules/nan-check/nan-check.h:360:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(args.Length(), count);
                ^
../node_modules/nan-check/nan-check.h:371:17: error: cannot use 'throw' with exceptions disabled
                throw CheckException(args.Length(), { argsCount1, argsCount2 });
                ^
../node_modules/nan-check/nan-check.h:393:9: error: cannot use 'try' with exceptions disabled
        try
        ^
../node_modules/nan-check/nan-check.h:427:16: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
        return std::move(CheckArguments(args));
               ^
../node_modules/nan-check/nan-check.h:427:16: note: remove std::move call here
        return std::move(CheckArguments(args));
               ^~~~~~~~~~                    ~
In file included from ../src/edflib_wrapper.cc:4:
../src/edf_wrapper.h:361:7: error: cannot use 'throw' with exceptions disabled
                                                throw std::logic_error(ERR_WRONG_SIGNAL_LENGTH);
                                                ^
../src/edf_wrapper.h:364:10: error: cannot use 'throw' with exceptions disabled
                                else throw std::logic_error(ERR_NOT_ARRAY);
                                     ^
../src/edf_wrapper.h:369:5: error: cannot use 'throw' with exceptions disabled
                                throw std::logic_error(ERR_WRONG_SIGNAL_LENGTH);
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/edflib/src/edflib_wrapper.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/andrewkeller/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrewkeller/dev/node-edflib
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/Users/andrewkeller/.npm-packages/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-edflib@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-edflib@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-edflib package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-edflib
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-edflib
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewkeller/dev/node-edflib/npm-debug.log
```

**Comment by maxsivkov** [comment]
I tested it under linux(gcc)  and Win (MSVC 2017)
I will try to test it under mac, but it will take some time...

**Comment by maxsivkov** [comment]
@aj-ptw 
I was able to build library for macosx 10.11. Please checkout **macos_fixes** branch
https://github.com/maxsivkov/node-edflib/tree/macos_fixes
For the moment all tests work fine, but for some reason calling _GetVersion_ produces segmentation fault:(

Please try macos_fixes branch

**Comment by aj-ptw** [comment]
@maxsivkov hi thanks for all your efforts!!!

The library is now installing (compiling) under the [macos_fixes](https://github.com/maxsivkov/node-edflib/tree/macos_fixes).

**Comment by andrewjaykeller** [comment]
I'm going to close this once the `macos_fixes` is merged because it is compiling but the `test-edf.js` is seg faulting.
